config/routes.rb
Rails.application.routes.draw do

  # AUTENTICAÇÃO E HOME
  root 'home#index'
  get '/login' => 'login#login'
  post '/login' => 'login#logar'
  get '/logout' => 'login#logout', as: 'logout'
  get 'dados_pessoais' => 'home#dados_pessoais', as: 'dados_pessoais'
  post 'dados_pessoais' => 'home#salvar_dados_pessoais'

  # CADASTROS
  scope path_names: {edit: 'editar', new: 'novo'} do
    resources :usuarios, except: :show
    resources :campi, except: :show

    resources :calendarios, except: :show do
      resources :eventos
    end
  end
  resources :evento_tipos, only: :index

  # API
  get 'api/campi.:format' => 'api#campi', as: 'api_campi'
  get 'api/calendario/:id_campus.:format' => 'api#calendario', as: 'api_calendario'
end

app/models/calendario.rb
class Calendario < ActiveRecord::Base
  belongs_to :campus
  has_many :eventos, dependent: :restrict_with_exception

  validates_presence_of :nome, :vigencia, :campus

  def to_s
    nome
  end
end

app/controllers/calendarios_controller.rb
class CalendariosController < ApplicationController
  load_and_authorize_resource

  before_action :set_calendario, only: [:edit, :update, :destroy]

  def index
    @calendarios = Calendario.accessible_by(current_ability)
  end

  def new
    @calendario = Calendario.new
  end

  def edit
  end

  def create
    @calendario = Calendario.new(calendario_params)

    @calendario.campus = current_user.campus if cannot? :manage, Campus

    respond_to do |format|
      if @calendario.save
        format.html { redirect_to calendarios_path, notice: "Calendário #{@calendario.nome} cadastrado com sucesso." }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @calendario.update(calendario_params)
        format.html { redirect_to calendarios_path, notice: "Calendário #{@calendario.nome} atualizado com sucesso" }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    begin
      @calendario.destroy
      respond_to do |format|
        format.html { redirect_to calendarios_url, notice: "Calendário #{@calendario.nome} removido com sucesso." }
      end
    rescue ActiveRecord::DeleteRestrictionError
      respond_to do |format|
        format.html { redirect_to calendarios_url, notice: "O calendário #{@calendario.campus.sigla} - #{@calendario.nome} não pôde ser removido pois existem eventos registrados para ele." }
      end
    end
  end

  private
  def set_calendario
    @calendario = Calendario.find(params[:id])
  end

  def calendario_params
    params.require(:calendario).permit(:campus_id, :nome, :vigencia)
  end
end

app/helpers/calendarios_helper.rb
module CalendariosHelper
end

app/views/calendarios/_form.html.erb
<%= simple_form_for(@calendario) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.association :campus, prompt: 'Selecione um câmpus.', label: 'Câmpus' if can? :manage, Campus %>
      <%= f.input :nome %>
      <%= f.input :vigencia %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, 'Salvar', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/calendarios/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <h1 class="pull-left">
      <%= link_to calendarios_path, class: 'btn btn-back' do %>
          <i class="glyphicon glyphicon-chevron-left"></i>
      <% end %>
      Editar calendário
    </h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/calendarios/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <h1 class="pull-left">Listagem de calendários</h1>

    <div class="pull-right">
      <%= link_to new_calendario_path, class: 'btn btn-link btn-lg' do %>
          <i class="glyphicon glyphicon-plus"></i>
      <% end %>
    </div>
  </div>
  <% if @calendarios.any? %>
      <table class="table table-hover table-striped">
        <thead>
        <tr>
          <% if can? :manage, Campus %>
              <th>Câmpus</th>
          <% end %>
          <th>Nome</th>
          <th>Vigente a partir de</th>
          <th class="config"></th>
        </tr>
        </thead>

        <tbody>
        <% @calendarios.each do |calendario| %>
            <tr>
              <% if can? :manage, Campus %>
                  <td><%= calendario.campus %></td>
              <% end %>
              <td><%= calendario.nome %></td>
              <td><%= calendario.vigencia.strftime('%d/%m/%Y às %H:%M') %></td>
              <td class="text-nowrap">
                <%= link_to calendario_eventos_path(calendario), class: 'btn btn-xs btn-success', data: {toggle: 'tooltip', placement: 'top'}, title: 'Eventos' do %>
                    <i class="glyphicon glyphicon-list"></i>
                <% end %>
                <%= link_to edit_calendario_path(calendario), class: 'btn btn-xs btn-primary', data: {toggle: 'tooltip', placement: 'top'}, title: 'Editar' do %>
                    <i class="glyphicon glyphicon-edit"></i>
                <% end %>
                <%= link_to calendario, method: :delete, class: 'btn btn-xs btn-danger', data: {toggle: 'tooltip', placement: 'top', confirm: "Deseja realmente remover o calendário #{calendario.nome}?"}, title: 'Remover' do %>
                    <i class="glyphicon glyphicon-trash"></i>
                <% end %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
  <% else %>
      <div class="alert alert-info no-margin">
        Nenhum calendário cadastrado.
      </div>
  <% end %>
</div>

app/views/calendarios/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <h1 class="pull-left">
      <%= link_to calendarios_path, class: 'btn btn-back' do %>
          <i class="glyphicon glyphicon-chevron-left"></i>
      <% end %>
      Novo calendário
    </h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>