config/routes.rb
Rails.application.routes.draw do

  # AUTENTICAÇÃO E HOME
  root 'home#index'
  get '/login' => 'login#login'
  post '/login' => 'login#logar'
  get '/logout' => 'login#logout', as: 'logout'
  get 'dados_pessoais' => 'home#dados_pessoais', as: 'dados_pessoais'
  post 'dados_pessoais' => 'home#salvar_dados_pessoais'

  # CADASTROS
  scope path_names: {edit: 'editar', new: 'novo'} do
    resources :usuarios, except: :show
    resources :campi, except: :show

    resources :calendarios, except: :show do
      resources :eventos
    end
  end
  resources :evento_tipos, only: :index

  # API
  get 'api/campi.:format' => 'api#campi', as: 'api_campi'
  get 'api/calendario/:id_campus.:format' => 'api#calendario', as: 'api_calendario'
end

app/controllers/campi_controller.rb
class CampiController < ApplicationController
  load_and_authorize_resource

  before_action :set_campus, only: [:edit, :update, :destroy]

  def index
    @campi = Campus.all
  end

  def new
    @campus = Campus.new
  end

  def edit
  end

  def create
    @campus = Campus.new(campus_params)

    respond_to do |format|
      if @campus.save
        format.html { redirect_to campi_path, notice: "Câmpus #{@campus.sigla} criado com sucesso." }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @campus.update(campus_params)
        format.html { redirect_to campi_path, notice: "Câmpus #{@campus.sigla} atualizado com sucesso." }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    begin
      @campus.destroy
      respond_to do |format|
        format.html { redirect_to campi_url, notice: "Câmpus #{@campus.sigla} removido com sucesso." }
      end
    rescue ActiveRecord::DeleteRestrictionError
      respond_to do |format|
        format.html { redirect_to campi_url, notice: "O câmpus #{@campus.sigla} não pôde ser removido pois existem calendários registrados para ele." }
      end
    end
  end

  private
    def set_campus
      @campus = Campus.find(params[:id])
    end

    def campus_params
      params.require(:campus).permit(:nome, :sigla)
    end
end

app/helpers/campi_helper.rb
module CampiHelper
end

app/views/campi/_form.html.erb
<%= simple_form_for(@campus) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :nome %>
      <%= f.input :sigla %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, 'Salvar', class:'btn btn-primary' %>
    </div>
<% end %>

app/views/campi/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <h1 class="pull-left">
      <%= link_to campi_path, class: 'btn btn-back' do %>
          <i class="glyphicon glyphicon-chevron-left"></i>
      <% end %>
      Editar câmpus
    </h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/campi/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <h1 class="pull-left">Listagem de câmpus</h1>

    <div class="pull-right">
      <%= link_to new_campus_path, class: 'btn btn-link btn-lg' do %>
          <i class="glyphicon glyphicon-plus"></i>
      <% end %>
    </div>
  </div>
  <% if @campi.any? %>
      <table class="table table-hover table-striped">
        <thead>
        <tr>
          <th>Nome</th>
          <th>Sigla</th>
          <th class="config">
            <i class="glyphicon glyphicon-cog"></i>
          </th>
        </tr>
        </thead>

        <tbody>
        <% @campi.each do |campus| %>
            <tr>
              <td><%= campus.nome %></td>
              <td><%= campus.sigla %></td>
              <td class="text-nowrap">
                <%= link_to edit_campus_path(campus), class: 'btn btn-xs btn-info' do %>
                    <i class="glyphicon glyphicon-edit"></i>
                <% end %>

                <%= link_to campus, method: :delete, data: {confirm: "Deseja realmente excluir o câmpus #{campus.sigla}?"}, class: 'btn btn-xs btn-danger' do %>
                    <i class="glyphicon glyphicon-trash"></i>
                <% end %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
  <% else %>
      <div class="alert alert-info no-margin">
        Nenhum câmpus cadastrado.
      </div>
  <% end %>
</div>

app/views/campi/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <h1>
      <%= link_to campi_path, class:'btn btn-back' do %>
          <i class="glyphicon glyphicon-chevron-left"></i>
      <% end %>Novo câmpus
    </h1>

  </div>
  <div class="panel-body">

    <%= render 'form' %>
  </div>
</div>