config/routes.rb
Rails.application.routes.draw do

  # AUTENTICAÇÃO E HOME
  root 'home#index'
  get '/login' => 'login#login'
  post '/login' => 'login#logar'
  get '/logout' => 'login#logout', as: 'logout'
  get 'dados_pessoais' => 'home#dados_pessoais', as: 'dados_pessoais'
  post 'dados_pessoais' => 'home#salvar_dados_pessoais'

  # CADASTROS
  scope path_names: {edit: 'editar', new: 'novo'} do
    resources :usuarios, except: :show
    resources :campi, except: :show

    resources :calendarios, except: :show do
      resources :eventos
    end
  end
  resources :evento_tipos, only: :index

  # API
  get 'api/campi.:format' => 'api#campi', as: 'api_campi'
  get 'api/calendario/:id_campus.:format' => 'api#calendario', as: 'api_calendario'
end

app/models/evento.rb
class Evento < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :calendario
  belongs_to :evento_tipo

  validates_presence_of :evento_tipo, :calendario, :inicio, :fim

  validates_presence_of :dia_semana, if: -> (evento) { evento.evento_tipo.nil? or evento.evento_tipo.tem_dia_semana }

  before_validation :set_dia_fim

  def self.dias_semana
    [
        ['Domingo', 0],
        ['Segunda-Feira', 1],
        ['Terça-Feira', 2],
        ['Quarta-Feira', 3],
        ['Quinta-Feira', 4],
        ['Sexta-Feira', 5],
        ['Sábado', 6],
    ]
  end

  def self.vigentes(campus)
    joins(:calendario).where('calendarios.vigencia <= ? AND calendarios.campus_id = ?', Time.now, campus)
  end

  def self.from(timestamp)
    self.where('eventos.updated_at > ?', Time.at(timestamp))
  end

  def self.last_update
    self.pluck('MAX(updated_at)').first.to_i
  end

  def dia_semana_nome
    self.class.dias_semana.to_h.invert[self.dia_semana]
  end

  private
  def set_dia_fim
    self.fim = self.inicio unless self.evento_tipo.tem_periodo
  end
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  load_and_authorize_resource

  before_action :set_evento, only: [:show, :edit, :update, :destroy]
  before_action :set_calendario

  def index
    @eventos = @calendario.eventos.order(:inicio).order(:fim)
  end

  def show
  end

  def new
    @evento = @calendario.eventos.build
  end

  def edit
  end

  def create
    @evento = @calendario.eventos.build(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to calendario_eventos_path, notice: 'Evento cadastado com sucesso.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to calendario_eventos_path, notice: 'Evento atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to calendario_eventos_path, notice: 'Evento removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
  def set_evento
    @evento = Evento.find(params[:id])
  end

  def set_calendario
    @calendario = Calendario.accessible_by(current_ability).find(params[:calendario_id])
  end

  def evento_params
    params.require(:evento).permit(:evento_tipo_id, :inicio, :fim, :dia_semana, :descricao)
  end
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/views/eventos/_form.html.erb
<div ng-controller="eventosFormController as ctrl">
  <%= simple_form_for([@calendario, @evento], form_html: {class: 'form-horizontal'}) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :evento_tipo, as: :select, prompt: 'Selecione um tipo de evento.',
                    input_html: {:'ng-model' => 'evento.tipo',
                                 :'ng-options' => 'tipo.nome for tipo in ctrl.eventoTipos track by tipo.id'} %>
        <%= f.input_field :evento_tipo_id, as: :hidden %>
        <%= f.input :inicio, wrapper_html: {:'ng-if' => 'evento.tipo.id'} %>
        <%= f.input :fim, wrapper_html: {:'ng-if' => 'evento.tipo.tem_periodo'} %>
        <%= f.input :dia_semana, collection: Evento.dias_semana, prompt: 'Selecione um dia da semana.',
                    wrapper_html: {:'ng-if' => 'evento.tipo.tem_dia_semana'} %>
        <%= f.input :descricao, wrapper_html: {:'ng-if' => 'evento.tipo.tem_descricao'} %>
      </div>
      <div class="form-actions">
        <%= f.button :submit, 'Salvar', class: 'btn btn-primary' %>
      </div>
  <% end %>
</div>

app/views/eventos/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <h1 class="pull-left">
      <%= link_to calendario_eventos_path, class: 'btn btn-back' do %>
          <i class="glyphicon glyphicon-chevron-left"></i>
      <% end %>
      Editar evento
    </h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/eventos/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <h1 class="pull-left">
      <%= link_to calendarios_path, class: 'btn btn-back' do %>
          <i class="glyphicon glyphicon-chevron-left"></i>
      <% end %>
      Eventos do calendário <%= @calendario %>
    </h1>

    <div class="pull-right">
      <%= link_to new_calendario_evento_path, class: 'btn btn-link btn-lg' do %>
          <i class="glyphicon glyphicon-plus"></i>
      <% end %>
    </div>
  </div>
  <% if @eventos.any? %>
      <table class="table table-hover table-striped">
        <thead>
        <tr>
          <th>Evento tipo</th>
          <th class="text-center">Data</th>
          <th class="config">
            <i class="glyphicon glyphicon-cog"></i>
          </th>
        </tr>
        </thead>

        <tbody>
        <% @eventos.each do |evento| %>
            <tr>
              <td><%= evento.evento_tipo.to_s + (evento.evento_tipo.tem_dia_semana ? " (#{evento.dia_semana_nome})" : '') %></td>
              <% if evento.inicio == evento.fim %>
                  <td class="text-center"><%= evento.inicio.strftime '%d/%m/%Y' %></td>
              <% else %>
                  <td class="text-center"><%= evento.inicio.strftime '%d/%m/%Y' %> - <%= evento.fim.strftime '%d/%m/%Y' %></td>
              <% end %>
              <td class="text-nowrap">
                <%= link_to calendario_evento_path(@calendario, evento), class: 'btn btn-xs btn-success', data: {toggle: 'tooltip', placement: 'top'}, title: 'Visualizar' do %>
                    <i class="glyphicon glyphicon-list"></i>
                <% end %>
                <%= link_to edit_calendario_evento_path(@calendario, evento), class: 'btn btn-xs btn-primary', data: {toggle: 'tooltip', placement: 'top'}, title: 'Editar' do %>
                    <i class="glyphicon glyphicon-edit"></i>
                <% end %>
                <%= link_to [@calendario, evento], method: :delete, class: 'btn btn-xs btn-danger', data: {confirm: 'Deseja realmente remover este evento?', toggle: 'tooltip', placement: 'top'}, title: 'Eventos' do %>
                    <i class="glyphicon glyphicon-trash"></i>
                <% end %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>

  <% else %>
      <div class="alert alert-info no-margin">
        Nenhum evento cadastrado.
      </div>
  <% end %>
</div>

app/views/eventos/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <h1 class="pull-left">
      <%= link_to  calendario_eventos_path(@calendario), class: 'btn btn-back' do %>
          <i class="glyphicon glyphicon-chevron-left"></i>
      <% end %>
      Novo evento
    </h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/eventos/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <h1 class="pull-left">
      <%= link_to calendario_eventos_path(@evento.calendario), class: 'btn btn-back' do %>
          <i class="glyphicon glyphicon-chevron-left"></i>
      <% end %>
      Visualizar evento
    </h1>
  </div>
  <div class="panel-body">
    <p>
      <strong>Calendario:</strong>
      <%= @evento.calendario %>
    </p>

    <p>
      <strong>Evento tipo:</strong>
      <%= @evento.evento_tipo %>
    </p>

    <p>
      <strong>Inicio:</strong>
      <%= @evento.inicio.strftime '%d/%m/%Y' %>
    </p>

    <p>
      <strong>Fim:</strong>
      <%= @evento.fim.strftime '%d/%m/%Y' %>
    </p>
    <% if !@evento.dia_semana.blank? %>
        <p>
          <strong>Dia semana:</strong>
          <%= @evento.dia_semana %>
        </p>
    <% end %>
    <% if !@evento.descricao.blank? %>
        <p>
          <strong>Descrição:</strong>
          <%= @evento.descricao %>
        </p>
    <% end %>
  </div>
</div>'