config/routes.rb
Rails.application.routes.draw do

  # AUTENTICAÇÃO E HOME
  root 'home#index'
  get '/login' => 'login#login'
  post '/login' => 'login#logar'
  get '/logout' => 'login#logout', as: 'logout'
  get 'dados_pessoais' => 'home#dados_pessoais', as: 'dados_pessoais'
  post 'dados_pessoais' => 'home#salvar_dados_pessoais'

  # CADASTROS
  scope path_names: {edit: 'editar', new: 'novo'} do
    resources :usuarios, except: :show
    resources :campi, except: :show

    resources :calendarios, except: :show do
      resources :eventos
    end
  end
  resources :evento_tipos, only: :index

  # API
  get 'api/campi.:format' => 'api#campi', as: 'api_campi'
  get 'api/calendario/:id_campus.:format' => 'api#calendario', as: 'api_calendario'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Calendario Web</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
          Calendário<sup>
      <small>WEB</small>
    </sup>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if can? :manage, Campus %>
            <li>
              <%= link_to 'Câmpus', campi_path %>
            </li>
        <% end %>
        <li>
          <%= link_to 'Calendários', calendarios_path %>
        </li>
        <% if can? :manage, Usuario %>
            <li>
              <%= link_to 'Usuários', usuarios_path %>
            </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            Logado como
            <%= @active_user %>
            <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to 'Sair', logout_path %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to 'Alterar dados', dados_pessoais_path %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>
<div class="main-container">
  <% if notice %>
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= notice %>
      </div>
  <% end %>
  <div ng-app="calendarioWeb">
    <%= yield %>
  </div>
</div>

</body>
</html>